# Generated by Django 3.2.12 on 2025-01-30 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('date_achieved', models.DateField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='achievements/')),
                ('category', models.CharField(choices=[('Academics', 'Academics'), ('Sports', 'Sports'), ('Research', 'Research'), ('Entrepreneurship', 'Entrepreneurship'), ('Others', 'Others')], default='Others', max_length=100)),
                ('is_approved', models.BooleanField(default=True)),
                ('achiever', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_achieved'],
            },
        ),
    ]
