# Generated by Django 3.2.12 on 2025-01-31 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_alumni'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumni',
            options={'ordering': ['-graduation_year', 'name']},
        ),
        migrations.RenameField(
            model_name='alumni',
            old_name='batch',
            new_name='graduation_year',
        ),
        migrations.RenameField(
            model_name='alumni',
            old_name='phone',
            new_name='mobile',
        ),
        migrations.AddField(
            model_name='alumni',
            name='achievements',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='skills',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='location',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
