# Generated by Django 3.2.12 on 2025-01-31 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0004_auto_20250131_0405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='achiever',
        ),
        migrations.AlterField(
            model_name='alumni',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='alumni/'),
        ),
    ]
