# Generated by Django 3.2.12 on 2025-01-31 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0005_auto_20250131_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/alumni/'),
        ),
    ]
