# Generated by Django 3.2.12 on 2025-01-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0006_alter_alumni_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/achievements/'),
        ),
    ]
