# Generated by Django 3.2.12 on 2025-02-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0007_alter_achievement_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images/events/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('Conference', 'Conference'), ('Workshop', 'Workshop'), ('Seminar', 'Seminar'), ('Meetup', 'Meetup'), ('Others', 'Others')], default='Others', max_length=100)),
            ],
            options={
                'ordering': ['start_date', 'title'],
            },
        ),
        migrations.AlterField(
            model_name='newspage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/news_images/'),
        ),
    ]
