# Generated by Django 3.2.12 on 2025-02-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0009_opportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/opportunities/'),
        ),
    ]
